/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OOPA2;
 import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author drmongiello
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     */
    public static void reset()
    {
         try
        {
            Thread.sleep(3000); 
        }catch (InterruptedException e) {
    e.printStackTrace();
    }
    }
    
    public static void main(String args[]) throws ClassNotFoundException {
        
        // Change the look and feel to the user preference
        try{
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); 
        }
        catch (UnsupportedLookAndFeelException e){
            
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
      SwingUtilities.invokeLater(new Runnable()
      {public void run(){createAndShowGUI();}
            });
    }

         private static void createAndShowGUI(){
            System.out.println("Created GUI on EDT? " + SwingUtilities.isEventDispatchThread());
            JFrame f = new JFrame("Twitter Beta");
            // Set up the frame and defualts
            final CardLayout cardLayout = new CardLayout();
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            final Container contentPane = f.getContentPane();
            final String path = "src/javaapplication2/";
            contentPane.setLayout(cardLayout);
            final SplashPanel splashPanel = new SplashPanel();

            final MainScreen mainScreen = new MainScreen();
            
            contentPane.setPreferredSize(new Dimension(600,400));
            contentPane.add(splashPanel, "Splash Panel");
            contentPane.add(mainScreen, "Main Screen");
            // Set size of screen and make visiable
            f.setSize(600, 400);
            f.setLocationRelativeTo(null);
            f.pack();
            f.setVisible(true);
  
            Timer t = new Timer(3000, new UpdateClockAction( cardLayout, contentPane));
            t.setRepeats(false);
            t.start(); 
           
        }
        // All this timer stuff is for the splash screen action. 
        private static class UpdateClockAction implements ActionListener {
        private Timer t;
        private CardLayout c;
        private Container p;

        public UpdateClockAction( CardLayout cc,Container pp  ) 
        {
        c = cc;
        p = pp;
        }
    
        public void actionPerformed(ActionEvent e) {
            c.show(p, "Main Screen");
            
        }
    }
         
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


